import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import './globals.css'
import AppProvider from '../AppProvider'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {

  const messages = await getMessages()
  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')

  return (

    <html suppressHydrationWarning={true} lang={locale}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <AppProvider inititalSessionToken={sessionToken?.value} >
            {children}
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
